# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 22 Jul 2015 07:39:28 +0000
*               @ALL          1
*               @user         8
