<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: match
 * Date: Tue, 25 Aug 2015 05:40:48 +0000
 */

$conf['title'] = '睡眠知识库';
$conf['start'] = '开始';
$conf['lang'] = 'zh';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['manager'] = 'match';
$conf['disableactions'] = 'register';
$conf['remote'] = 1;
$conf['remoteuser'] = 'xmlrpc,anransleep';
$conf['userewrite'] = '1';
$conf['send404'] = 1;
$conf['dnslookups'] = 0;
$conf['proxy']['user'] = 'maggie';
$conf['proxy']['pass'] = '<b>Z2EwbTFhMG0xYTA=';
$conf['tpl']['bootstrap3']['showLoginOnFooter'] = 1;
$conf['tpl']['bootstrap3']['hideLoginLink'] = 1;

// end auto-generated content
