<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: match
 * Date: Wed, 22 Jul 2015 21:12:12 +0800
 */

$conf['title'] = '睡吧知识库';
$conf['start'] = '开始';
$conf['lang'] = 'zh';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';
$conf['tpl']['bootstrap3']['showLoginOnFooter'] = 1;

// end auto-generated content
